### PR TITLE
pep8 for recent commits

### PR DESCRIPTION
**Pull request by CodeMaxx**
I think veryone should download `yapf`(the latest one from github- version 0.10.0) and use it before sending in a PR. So that we don't have to make a separate PR for pep8 fixes.

This is another test we can add to Travis CI.

@Pratik151 @Ali-Razmjoo @jowasp

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hi akash, you right, i've got little bit lazy about this, BUT why this pep8 fixer is using spaces instead of tabs, this killing me which I can't understand seriously why!?

**Comment by Pratik151** [comment]
@Ali-Razmjoo  Yea I am seeing this much. There is many places where code is not looking good after pep8 fixes like [this](https://github.com/zscproject/OWASP-ZSC/blob/master/lib/opcoder/osx_x86.py)  because the lines are break after fixed number. and [this](https://github.com/zscproject/OWASP-ZSC/blob/1c8ab697b24b78cfbd1896e38afba4e626439d40/core/stack.py#L75)

**Comment by Ali-Razmjoo** [comment]
@CodeMaxx is there any config file in yapf to fix it? I mean replace tabs instead of spaces.

**Comment by CodeMaxx** [comment]
You can make a custom styling file for yapf. 
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

P.S. I use only spaces :P (Have a setting in my IDE to convert tabs to spaces so I don't have to press space 4 times infront of every line)

**Comment by CodeMaxx** [comment]
@Pratik151 For those kind of lines we can increase the max length of a line. It is 80 by default. I like to use 120 though.  We can decide how much we want.

**Comment by Pratik151** [comment]
@CodeMaxx  Yea I think it is better if we remove/increase max length of line. what do you say @Ali-Razmjoo

**Comment by Ali-Razmjoo** [comment]
I think that would be better, but please fix the spaces first.

**Comment by CodeMaxx** [comment]
But why do we want tabs in place of spaces?

**Comment by paraschetal** [comment]
Tabs vs spaces is a battle which has been going on for a long time :P . I for one prefer tabs for indentation. Both have their advantages and disadvantages.
Here's a fun video on the topic from the Silicon Valley TV series :P : 
https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by Ali-Razmjoo** [comment]
Tabs works fine in all ide and editors, I personally use notepad++, and spaces won't work there, i must push for spaces, but tabs are fine everywhere.

**Comment by CodeMaxx** [comment]
@Ali-Razmjoo Actually on the other hand the size of tabs is different in different editors. Some keep it equal to 8 spaces and some 4 spaces which causes problems. That is why I think pep8 tells us to use spaces. 
Notepad++ can be easily configured( http://stackoverflow.com/questions/8197812/how-does-one-configure-notepad-to-use-spaces-instead-of-tabs ) . You can use this setting. Then you won't have to worry about it and you can use tabs just as before.

**Comment by Ali-Razmjoo** [comment]
I'm still not cool with spaces, it made the project size larger.every tabs converted to 4bytes of space. Johanna is testing the software to find bugs now, we can't change the old files now, but let's discuss it after demo labs. there is many spaces need to be change by tabs :D

**Comment by Ali-Razmjoo** [comment]
whole projec needs new refactor.

**Pull request closed without merging**
